# Generated by Django 3.2.4 on 2021-07-01 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board_app', '0002_alter_board_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='mainphoto',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
