# Generated by Django 3.2.4 on 2021-07-01 17:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('board_app', '0003_board_mainphoto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='board',
            name='mainphoto',
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mainphoto', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('post', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='board_app.board')),
            ],
        ),
    ]
