# Generated by Django 3.2.4 on 2021-07-01 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board_app', '0004_auto_20210701_1716'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='mainphoto',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
