# Generated by Django 3.2.4 on 2021-07-01 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board_app', '0005_board_mainphoto'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='category',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='board',
            name='color',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='board',
            name='location',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
